spring:
  redis:
    host: 127.0.0.1
    port: 6380
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/Text?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 13468724917qkm,
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
p6spy:
  config:
    appender: com.p6spy.engine.spy.appender.Slf4JLogger
    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
    customLogMessageFormat: executionTime:%(executionTime)| 执行sql:%(sqlSingleLine)
    executionThreshold: 20